apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-secret
  template:
    metadata:
      labels:
        app: flask-secret
    spec:
      containers:
      - name: flask-container
        image: YOUR_USERNAME/flask-secret-app
        ports:
        - containerPort: 80
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASS

---
apiVersion: v1
kind: Service
metadata:
  name: flask-secret-service
spec:
  type: NodePort
  selector:
    app: flask-secret
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082
